paginate: 5

title: 'An abelian grape'
description: 'News on recent mathematics progress, updates about my own research.'
author: 'synthels'

markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
