google_id: ''

menu:
- {name: 'Home', url: ''}
- {name: 'About', url: 'about'}

social:
- {icon: 'github',    style: 'brands', link: 'https://github.com/synthels'}
- {icon: 'youtube',   style: 'brands', link: 'https://youtube.com/@synthels'}
- {icon: 'bluesky',   style: 'brands', link: 'https://bsky.app/profile/synthels.bsky.social'}
- {icon: 'envelope',  style: 'solid',  link: 'mailto:synthels.me@gmail.com'}
- {icon: 'rss',       style: 'solid',  link: '/feed.xml'}

pagination:
  next_page: 'Next'
  previous_page: 'Previous'

post_date_prefix: 'Posted on'
